server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: invoice-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/invoices/**
        - id: order-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/orders/**
        - id: product-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/products/**
        - id: customer-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/customers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

